name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker image build -t Mahmoudmansourr/git_django:latest .
        docker push Mahmoudmansourr/git_django:latest
